### PR TITLE
Add installation split for debian stretch

### PR DESCRIPTION
**Pull request by sgutermann**
Edit messages to what you see fit.

### CODE REVIEW

**Comment by sgutermann** [comment]
Sorry, meant to kill the old one and make this a new one. This works fine for me on a fresh minimal install of debian stretch. 

I did not really touch or test the ubuntu stuff, aside from the split on the detection.

**Comment by sgutermann** [comment]
Is there still something needed from my part before this can get merged?

**Comment by mpdehaan** [comment]
You're good - I took last week off and hope to get to these this week.

**Comment by mpdehaan** [comment]
Hey, quick note... Looks like there is a sudo check still on the master branch.  This breaks on OS X, and claims my account does not have sudo rights when it does.  I'm going to cherry pick only the OS detection commit and just remove the message about the other thing.

**Comment by mpdehaan** [comment]
Ok, all merged, thank you!

Quick git FYI - In the future, I'd recommend starting a new branch per pull request rather than using "master" on your end, as the extra commit you have on there is no longer something we need upstream and will automatically appear on any new PRs from your master branch copy.

I just deleted the sudo check I had in there, which should do the same thing.

Thank you!

**Comment by sgutermann** [comment]
On the sudo thing, sorry. I checked this on my Linux end with sudo into sudo into sudo and had no perceivable problems.

Starting a new Branch, ok. Like I warned you I am new to this GitHub Pull Request thing, so I will watch for that next time.

Thank you!

**Pull request closed without merging**
