### PR TITLE
[WIP] Introduce archlinux support

### PR DESCRIPTION
**Pull request by 4383**
Adding support of archlinux.

## Test this feature localy
```
$ docker run --rm -it archlinux/base /bin/bash
# pacman --noconfirm -Sy git
# git clone -b introduce-archlinux https://github.com/4383/vespene.git ./vespene
# cd vespene/setup
# bash 1_prepare.sh # ok
# bash 2_database.sh # under construct
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
WOW, that was quick.  Awesome.

I'll be merging this shortly, thank you!

**Comment by 4383** [comment]
@mpdehaan I'm glad you appreciate this feature :)
Coming soon!

**Comment by mpdehaan** [comment]
Ok, this looks good, a few small things so I understand it.

- I think it makes sense to enable postgres for everyone, not just arch.

- Can you explain why the database setup is different with pam vs md5?   It's been a while since I've dealt with pam, but are the md5 modes installed and available?  Does that mean you need to create t he user a different way?

I'm happy to make the change to the first part on top of  your patch, up to you... though I want to understand the second before I apply it since I wouldn't think that was OS specific, but maybe it is.

Thanks!

**Comment by 4383** [comment]
@mpdehaan my responses:
- Yep it makes sense to enable postgres for everyone.
- concerning the pam mode instead of the md5 mode it's just a test, do not longer consider this. for your informations I currently follow [these instructions](https://wiki.archlinux.org/index.php/PostgreSQL)

On the other hand my docker method used to develop this feature show its limits... I'm facing an issue on it with systemctl and postgres service management... I currently switching my running context to continue my tests and when I will obtain a stable test environment I will share it with you like the previous commands format

**Comment by 4383** [comment]
A good implementation of this will be to provide integrated test directly on CI like travis on an other provdier with a run of the setup on all the supported environments but first we need to fix the systemctl issue on inside the container to provide this.

**Comment by 4383** [comment]
Well, seems to be ready!

So I switch from docker to vagrant to avoid quickly the systemctl issue.
Below the commands to use:
```
$ # Assume I use fedora 28
$ sudo dnf install vagrant libvirt
$ mkdir ~/vm
$ cd vm
$ vagrant init archlinux/archlinux
$ vagrant up
$ vagrant ssh
[vagrant@archlinux ~]$ sudo pacman --noconfirm -Sy git
[vagrant@archlinux ~]$  git clone -b introduce-archlinux https://github.com/4383/vespene.git ./vespene
[vagrant@archlinux ~]$ cd vespene/setup/
[vagrant@archlinux ~]$ sudo bash 1_prepare.sh
[vagrant@archlinux ~]$ sudo bash 2_database.sh 
[vagrant@archlinux ~]$ sudo bash 3_application.sh 
[vagrant@archlinux ~]$ sudo bash 4_superuser.sh 
[vagrant@archlinux ~]$ sudo bash 5_tutorial.sh 
[vagrant@archlinux ~]$ sudo bash 6_services.sh 
...
Vespene is now running on port 8000 and also running workers: tutorial-pool=1
```

@mpdehaan can you do make some tests and notice to me if everything it's ok on your side.
If it work fine I remove the WIP status

**Comment by 4383** [comment]
Note that we had a warning during the execution of the 2_database when we execute the tasks:
- creating the vespene database and user...
- granting access

I guess it's due to the usage of sudo with the vagrant user because when I run it with the following commands the warnings (`could not change directory to "/home/vagrant/vespene/setup": Permission denied`) doesn't appears:
```
$ sudo -u postgres -i
$ createdb vespene
```

**Comment by 4383** [comment]
Also I've take a look on how to automatise `vagrant` test with a service like travis-ci but it's not yet available... https://github.com/travis-ci/travis-ci/issues/6060

Well, cheers!

**Comment by mpdehaan** [comment]
Perfect, thank you!

**Pull request merged**
