### PR TITLE
Remove redundant all() calls in webhooks.py

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice catch - Interesting you can get away with calling all twice for sure :)  I'll test this sometime tomorrow.

Seeing you were looking at the webhook code, I wanted to ask if you had any problems with the GitHub integration or were possibly looking at adding support for other webhooks than GitHub?

One thing I wanted to add was an option on the project to allow the webhook to trigger any branch that came in *from* the webhook, which would enable some testing of feature branches.  (So use the branch name from the webhook, don't just only run if the branch matches).

This option would probably be named something like "webhooks_on_any_branch".  I'll file a ticket on this one.

**Comment by mpdehaan** [comment]
This feature is #84, I'll take care of this before I look at that.

**Comment by berkerpeksag** [comment]
Thank you for the quick review!

> Seeing you were looking at the webhook code, I wanted to ask if you had any problems with the GitHub integration or were possibly looking at adding support for other webhooks than GitHub?

I was just curious about how webhooks implemented in Vespene as I recently wrote a similar feature for a different software (in my case, I had to support webhooks of multiple services)

**Comment by mpdehaan** [comment]
Ah yes, got it.  Basically I just read the GitHub docs and tested it out, and then read the GitLab docs and didn't (it may work, I don't know!) figuring people with other systems would probably improve it more over time.

I decided to not trust the project names and just go off the repo URLs, which at least works if they match exactly, which they seem like they will.  (They especially will if imported from the .vespene files).

Seems to mostly be ok.

I know some build systems have periodic polling features for those that don't want to route webhooks, but so far I haven't heard of much interest in that so I think most people are ok with making sure there is connectivity.

**Comment by mpdehaan** [comment]
Note: I very clearly didn't get to this tomorrow, but I see no problem with this one.  I'll make a pass through pull requests soon.

If you ever wish to add any other webhook stuff (or anything else), you are definitely welcome.  What I started with was pretty basic.

**Comment by berkerpeksag** [comment]
@mpdehaan is there anything I can do to get this in? Thanks!

**Comment by mpdehaan** [comment]
I’ll be hopefully merging Vespene patches tomorrow if not sooner. Thanks!

**Pull request merged**
