### PR TITLE
Correct the wording for scm_login help_text

### PR DESCRIPTION
**Pull request by sm4rk0**
SSH tab is not next to the Repository tab, however there's this hint below the `Scm login` drop down:
`... or add an SSH key in the next tab`
Or even better, create a link to SSH tab, if supported.
Not sure, so left plain text.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Yeah, that's all evolved.  Probably good to not assume anything about what tab something is in because it might change - I suspect we'll always have tabs, but honestly, I don't know :)

Probably just want to say maybe just "add an SSH key"?

**Comment by sm4rk0** [comment]
Right, that's more future-proof. I'll update the PR.

**Comment by sm4rk0** [comment]
Wait, there's a typo...

**Comment by mpdehaan** [comment]
perfect, thanks!

**Pull request merged**
