### PR TITLE
[WIP] Introduce OpenSuse Support

### PR DESCRIPTION
**Pull request by kdbeall**
Noticed the previous code might break if the user has installed Python in a non-standard directory.
Hope this helps!

### CODE REVIEW

**Comment by kdbeall** [comment]
Need to remove echo statements whoops

**Comment by mpdehaan** [comment]
Hey @kdbeall !

Good to see you here!

Thanks for the patch.  While generally I like the idea of being a little more flexible, I also only test on a few limited platforms and think eventually there are going to be *other* blocks of code in there that set other OS specific behaviors.  One of those, for instance, might be what the init system is.

So, I guess my question is, was there a specific problem you were trying to deal with, or trying to get it running on a particular OS?

If so, that might influence how I'd think about solving it.

But I still want the OS detection to think about what OSes are supported or not - things like FreeBSD and Arch are going to come soon, and they are wildly different, so if we don't hit the "if" clauses because it found which, that wouldn't set out what I meant for this to grow into.

Somewhat make sense?

I also want to fix your issue though, so let me know.

**Comment by kdbeall** [comment]
@mpdehaan I'm trying to get this run on OpenSuse. There's a few issues. The *0_common.sh* script detects the distro as being Ubuntu being /usr/bin/apt exists. However, *apt* in OpenSuse is a Perl script that wraps around OpenSuse's own package manager *zypper*. The failure occurs in *1_prepare.sh* when trying to install the *supervisor* package --- which doesn't exist in OpenSuse's repository.

**Comment by mpdehaan** [comment]
Thanks for the explanation!  OpenSuSE support would be awesome.

My feeling is you should add a check for zypper prior to the apt clause, unless there's something that's a better thing to check for like /etc/suse-release or something.  I don't recall as it is has been a long while since I wrote distro check code.

**Comment by kdbeall** [comment]
Shamelessly taken from @4383!
$ vagrant init generic/opensuse42
$ vagrant up
$ vagrant ssh # connect to opensuse with vagrant
[vagrant@opensuse42 ~]$ sudo zypper install -y git
[vagrant@opensuse42 ~]$ git clone -b opensuse-setup https://github.com/kdbeall/vespene.git ./vespene
[vagrant@opensuse42 ~]$ cd vespene/setup/
[vagrant@opensuse42 ~]$ sudo bash 1_prepare.sh
[vagrant@opensuse42 ~]$ sudo bash 2_database.sh 
[vagrant@opensuse42 ~]$ sudo bash 3_application.sh 
[vagrant@opensuse42 ~]$ sudo bash 4_superuser.sh 
[vagrant@archlinux ~]$ sudo bash 5_tutorial.sh 
[vagrant@archlinux ~]$ sudo bash 6_services.sh

**Comment by kdbeall** [comment]
@mpdehaan I think this is ready to be merged into master! Tested using vagrant.

**Comment by mpdehaan** [comment]
Hey thanks!  Unfortunately I have just screwed you up per https://talk.vespene.io/t/setup-overhaul-app-now-runs-as-vespene-on-linux-os-x-homebrew-setup-etc/35/2 - do you mind trying to re-apply your changes?

It might be easier to do them on a new branch.

I'm curious if all of the other steps are working?

Thanks very much!

**Comment by kdbeall** [comment]
Yeah, something is broken! I think I found where it's broken. Most distros nowadays like [https://askubuntu.com/questions/345974/what-is-the-difference-between-adduser-and-useradd](Ubuntu) have an *adduser* command but OpenSUSE by default only has *useradd*.

**Comment by kdbeall** [comment]
Was working though! :smile: I was too lazy to do some things to forward X11 so tried it out in Lynx browser.

**Comment by kdbeall** [comment]
@mpdehaan Fixed the issue!

**Comment by 4383** [comment]
@kdbeall I guess you need to change your pull request target branch to the new `new_setup`

**Comment by 4383** [comment]
I think you need to squash your commits to simplify revert if it needed in the futur

**Comment by mpdehaan** [comment]
new_setup is going to be deleted soon, that's already merged to master.

Will take a look, thanks... I need to confirm useradd vs adduser isn't an issue in other distros.  This is why I wrote a config management tool LOL -- but yeah, I have reasons to not want to use that as well :)

Awesome.

**Comment by mpdehaan** [comment]
Also, git tip, alias "git pull" to "git pull --rebase", and you won't have any more merge commits in your git history.

**Comment by mpdehaan** [comment]
I looked up useradd vs adduser and that was educational :)

useradd is the more low level one and I just committed a fix to use that everywhere.  Sometimes adduser goes interactive and asks questions about user names, and we definitely don't need that here, so good deal

**Pull request closed without merging**
