### PR TITLE
Added support for aarch64

### PR DESCRIPTION
**Pull request by fsbano**
Vespene on CentOS 7.x - armv8-ARM64-AArch64  - Quad-Core ARM Cortex A53 64-Bit Processor and support up to 4GB 1600MHz LPDDR3 memory

- https://www.pine64.org/?product=rock64-media-board-computer
- http://en.t-firefly.com/product/rocrk3328cc

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi @fsbano - nice to see interest in more platforms - I'm curious as I don't have access to this hardware at the moment, does this distro automatically ship with that repo enabled and can the rest of the install steps (1-6) finish out without error?

I can see where the software collections repo might not have postgresql (fine) but it's also not installing python and supervisor, so I wanted to make sure about that part.

**Comment by fsbano** [comment]
> Hi @fsbano - nice to see interest in more platforms - I'm curious as I don't have access to this hardware at the moment, does this distro automatically ship with that repo enabled and can the rest of the install steps (1-6) finish out without error?
> 
> I can see where the software collections repo might not have postgresql (fine) but it's also not installing python and supervisor, so I wanted to make sure about that part.

I built the rpm for aarch64 and I'm working on the other files

see below
[root@voyager aarch64]# ls -1 
postgresql10-10.5-1PGDG.el7.aarch64.rpm
postgresql10-contrib-10.5-1PGDG.el7.aarch64.rpm
postgresql10-debuginfo-10.5-1PGDG.el7.aarch64.rpm
postgresql10-devel-10.5-1PGDG.el7.aarch64.rpm
postgresql10-docs-10.5-1PGDG.el7.aarch64.rpm
postgresql10-libs-10.5-1PGDG.el7.aarch64.rpm
postgresql10-plperl-10.5-1PGDG.el7.aarch64.rpm
postgresql10-plpython-10.5-1PGDG.el7.aarch64.rpm
postgresql10-pltcl-10.5-1PGDG.el7.aarch64.rpm
postgresql10-server-10.5-1PGDG.el7.aarch64.rpm
postgresql10-test-10.5-1PGDG.el7.aarch64.rpm
[root@voyager aarch64]# 

```
[root@voyager aarch64]# ps -ef | grep vespene ; uname -rm ; lscpu
vespene   3404     1  0 15:00 ?        00:00:10 /usr/bin/python /usr/bin/supervisord -n -c /etc/vespene/supervisord.conf
vespene   3407  3404  1 15:00 ?        00:02:24 /usr/bin/python3.6 manage.py worker tutorial-pool
vespene   3408  3404  0 15:00 ?        00:00:08 /bin/python36 /usr/local/bin/gunicorn --bind 192.168.2.5:8000 vespene.wsgi
vespene   3409  3407  0 15:00 ?        00:00:00 /usr/bin/ssh-agent /usr/bin/python3.6 manage.py worker tutorial-pool
vespene   3413  3408  0 15:00 ?        00:00:12 /bin/python36 /usr/local/bin/gunicorn --bind 192.168.2.5:8000 vespene.wsgi
postgres  3416 26404  0 15:00 ?        00:00:31 postgres: vespene vespene 127.0.0.1(36694) idle
root      6824  6769  0 17:59 pts/0    00:00:00 grep --color=auto vespene
4.18.16 aarch64
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model:                 4
CPU max MHz:           1296.0000
CPU min MHz:           408.0000
BogoMIPS:              48.00
L1d cache:             unknown size
L1i cache:             unknown size
L2 cache:              unknown size
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
[root@voyager aarch64]# 
```

**Comment by mpdehaan** [comment]
Ok, let me hold off on this until you get done with getting the full install through, and we can see where to go from there.  If it just outputs a message that you need to build it (maybe with instructions) that might be ok.

I just fought through all the software collection stuff last night and someone mentioned maybe using the RPMs from PostgreSQL directly would be easier, and that might allow ripping out all the PG_PREFIX stuff. If you want to give that a shot it may make the scripts cleaner and that wouldn't be a bad thing.

Thanks!

**Comment by mpdehaan** [comment]
Pull request for everything sounds good.

"Can I contribute in building the script for aarch64?"

I'm sorry, I'm not following this part, as I thought this is what we were talking about :) If not, let me know!

**Comment by fsbano** [comment]
> Pull request for everything sounds good.
> 
> "Can I contribute in building the script for aarch64?"
> 
> I'm sorry, I'm not following this part, as I thought this is what we were talking about :) If not, let me know!

I'm happy to be able to help :-)

Thanks!

**Comment by fsbano** [comment]
Hi, Michael DeHaan

Now it's as expected :-)

Best Regards,
Fábio Sbano

**Comment by mpdehaan** [comment]
Hi, I appreciate this work, but I feel I can't accept inclusion of RPMs from your private github binaries here, while I trust you are up to only good things, there is no guarantee those remain secure or correct and it becomes difficult should they ever need an update.

Grabbing the upstream RPMs and building them from source might be ok.  (rpm-build, etc)

There is also some duplication, such as the installation of python36 in two seperate places.

Further, this line looks like it could never succeed:

        sudo python36 -m ensurepip
        sudo yum install -y gcc python36 python36-devel supervisor libffi-devel openssl-devel

Why?  It tries to use python36 before it is installed.

I think the *BEST* solution would be to work with the aarch64 sig to get those RPMs available in software collections, or *ALTERNATIVELY* move all of Red Hat to use rpms from postgresql (recompiling on aarch64 if need be).

We also *really* don't need to install the server on machines in the "1" shell script, we were only doing that before because software collections just made the one package available.  If we are doing seperate RPMs, the Vespene nodes only need the libraries and clients.

If we choose to NOT adopt the postgresql RPMs, I've also been told there's a "-syspaths" RPM that would allow removal of all the $PG_PREFIX stuff.

Let me know if you have questions.  As I can't merge this right now, I'm going to close this ticket, feel free to open up a topic on the development forum (talk.vespene.io) if you would like to discuss details... I may not get notifications on this ticket and I need to figure out why that is :)

**Comment by fsbano** [comment]
> Hi, I appreciate this work, but I feel I can't accept inclusion of RPMs from your private github binaries here, while I trust you are up to only good things, there is no guarantee those remain secure or correct and it becomes difficult should they ever need an update.
> 
> Grabbing the upstream RPMs and building them from source might be ok. (rpm-build, etc)
> 
> There is also some duplication, such as the installation of python36 in two seperate places.
> 
> Further, this line looks like it could never succeed:
> 
> ```
>     sudo python36 -m ensurepip
>     sudo yum install -y gcc python36 python36-devel supervisor libffi-devel openssl-devel
> ```
> Why? It tries to use python36 before it is installed.
> 
> I think the _BEST_ solution would be to work with the aarch64 sig to get those RPMs available in software collections, or _ALTERNATIVELY_ move all of Red Hat to use rpms from postgresql (recompiling on aarch64 if need be).
> 
> We also _really_ don't need to install the server on machines in the "1" shell script, we were only doing that before because software collections just made the one package available. If we are doing seperate RPMs, the Vespene nodes only need the libraries and clients.
> 
> If we choose to NOT adopt the postgresql RPMs, I've also been told there's a "-syspaths" RPM that would allow removal of all the $PG_PREFIX stuff.
> 
> Let me know if you have questions. As I can't merge this right now, I'm going to close this ticket, feel free to open up a topic on the development forum (talk.vespene.io) if you would like to discuss details... I may not get notifications on this ticket and I need to figure out why that is :)

Okay.. no problem, I understand :)
But I'm using CentOS Core minimal and on "python36 -m pip -r requirements.txt.." I have a problem with it 
 
- psycopg2-binary==2.7.5 # ${PG_HOME} 
- cryptography # (openssl-dev)
- libffi-devel

```
sudo python36 -m ensurepip
sudo yum install -y gcc python36 python36-devel supervisor libffi-devel openssl-devel
```

Best Regards,
Fábio Sbano

**Pull request closed without merging**
