### PR TITLE
distribute with pypi and automatize installation and run

### PR DESCRIPTION
**Pull request by 4383**
Introducing vespene CLI:
    - run to run vespene
    - install to install vespene
    - config to configure install
    - tutorial to execute tutorial step during install

**Currently under construct**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Wow, this is sharp, and I'm impressed.  Needs some edits.  Most of my comments involve the parts about PyPi, but the core of this can stay.

I think including it in PyPi is something I would *eventually* might like to do, but... in development stage, that would mean a lot of pushing of updates.  It doesn't take into account that people may want to install the development latest or a stable branch (when we do that), and it also doesn't allow for instructions on a pure source install when setup is down.

Another reason the setup scripts were split up is Vespene is often going to be deployed on multiple machines where the database step only needs to install postgresql on one node - or otherwise might be skipped if PostgreSQL was already installed.  

I also do not want to *at this time* have PyPi instructions that remove all the hard work on the docs to explain the setup scripts, because those setup scripts work for *all branches* and not just PyPi.

PyPi typically allows only pushing one specific branch, and would be controlled by who owns PyPi (me), where as having instructions that work with any branch allows everyone to work on their own development branches easier.

Sure, they could run setup.py *TRUE*, but it's still an extra level to debug.

It looks like you are working on this a LOT and that is FANTASTIC, but I also don't want people to waste efforts, so I'd always encourage a discussion about ideas first on talk.vespene.io, mostly because I always feel a little bad when I disagree with large pull requests knowing they took a lot of time.

Reviewing the setup.py, I'd also mention there is no way this works on Python 2.7 :)

So,how do we go forward?

I do like *MOST* of this, but I think the instructions could reference building your own tarball for now - and we can push to PyPi later.

The database install call should be an optional config step, maybe, like the excellent wrapper you have on vespene config for the workers.

What I think you should do is include a seperate README (that I'll later merge in with docs) - it can be short, about how this works.  But don't edit my docs *YET*.  We should also include the instructions about making the setup.py tarball and how to do that versus installing from PyPi, as for the first several months I don't expect to have a stable version there.

It also needs to split out the 2_database step and make that a CLI command.

If we split out the database, this means the *after database* steps also have to be a "vespene" command like "finish_setup" or whatever.

It also seems like we would maybe want to eventually wrap the other useful management commands like "python manage.py migrate"

In all I want to be clear this is AWESOME - I just think we need to concentrate on the PyPi case and split out the commands to not assume it is a single node install, and later we can tweak the docs.

So like run pip locally in the docs for now after doing "python[3] setup.py bdist" or whatever, right?

Thoughts?

**Comment by mpdehaan** [comment]
Thinking about this some more, another potential problem is not all distros have python 3 installed by default, and 1_prepare.sh takes care of that.

So maybe we *don't* want to do this because it makes it harder for non-python audiences to sort out.

**Comment by 4383** [comment]
@mpdehaan normaly all my stuffs are compatibles python 2 and python 3 so the python version is not an issue. My stuff work with the both versions including setup.cfg, pbr is an openstack module and currently openstack need to be runned on a kind of system like RHEL, centos, ubuntu, etc... and the of python availables on these systems diverges from 2 to 3, depending on the distros.

I totally agree your opinions about splitting database, etc... we need to most properly design the wrapper to match with current setup script and use cases of these script.

Concerning pypi we are not obliged to push on it at start, in other words these features only introduce a standard python package installation like `python setup.py install` or `python -m pip install .` .

Concerning contributions on vespene users are not obliged to install vespene from pypi and user can easly continue to hack on vespene by using the following commands:
``` shell
git clone https://github.com/vespene-io/vespene/
cd vespene
pipenv shell
python -m pip install pbr
python -m pip install -e .[devel]
```

Ok for the docs I move my doc inside an another document to keep current install independent. You are right and it's more simple to draft our commands and our installations.

I'm away today, tomorrow I try to start to modify my current stuffs.

Do you have comment concerning my responses?

**Comment by 4383** [comment]
What does mean the p=3 label?

**Comment by mpdehaan** [comment]
Yeah it is just a priority.  I am using it very loosely at the moment, like "p=1" is work on this next, it's a big deal for bugs or marketability or something.

If we can sort out the split database part I think we can still get this in pretty quick.

I agree with python -m pip install git+https://github.com/vespene-io/vespene for development but to work from any branch I think the better route seems to be for the scripts to do:

python setup.py bdist
python setup.py install <path>

That way any branch works

We would need instructions for each "supported" distro on how to install python 3 (if need be) plus pip though, because that is something 1_prepare.sh used to take care of.

How does that sound?

**Comment by 4383** [comment]
@mpdehaan yep on archlinux and I guess on all the minimal distros like archlinux we need to install python manually, so yep we need to describe this step inside the documentation.

An another way would be to provide an shell script that user run to install vespene and this script only run the 1_prepare.sh step, example:
```shell
$ curl https://github.com/vespene-io/vespene/blob/master/install.sh | sh
Installing python
Installing vespene...
$ vespene --help
```
A lot of mainstream tools use this way, the installation is straighforward, also we can easily provide an installation based on the branch name just by switching it in the url...

Concerning development on vespene we should not install vespene with pip from github (`python -m pip install git+https://github.com/vespene-io/vespene`) this is only for final user not for contributor.

To hack on vespene, users need to clone with git, and after this to `git checkout` the right branch to work on explicitly. 

So, we have a lot of alternatives to install properly vespene for different use cases and in a relatively simple way.

**Comment by mpdehaan** [comment]
Here's my thinking - While the development user should follow the development guide, there are also people who will want to run from the master branch (right now this is all there is).  This was TONS of people with ansible for instance. So we need to account for that in the install script. 

curl | pipe bash can be pretty scary to a lot of engineers and I'd rather avoid endorsing that based on what I've said in the past :)

The install script requiring a parameter might be reasonable.

Download the script, read the script, execute it with "-branch <branch_name>", etc.

Definitely needs to setup python 3 if there is no Python 3.

Thoughts?

**Comment by 4383** [comment]
```shell
$ vagrant init ubuntu/ubuntu
$ vagrant up
$ vagrant ssh # connect to archlinux with vagrant
[vagrant@archlinux ~]$ curl https://raw.githubusercontent.com/4383/vespene/packaging/install.sh > install.sh
[vagrant@archlinux ~]$ sudo bash install.sh --repo=4383 --branch=packaging
[vagrant@archlinux ~]$ sudo vespene setup
```

**Comment by 4383** [comment]
Well @mpdehaan , I think I reach my goal.

- Install script is optional.
- Install can install from an another branch
- Install can install from an another repo (fork)
- database setup step can be run undependently from the others
- we can run a full install in one node simply by running `vespene setup`
- we can skip the tutorial by using `vespene setup --skip-tutorial`

I made the choice to implement config in an another PR to be focus on install and to do not continue to use this PR during lot of days to avoid rebases and conflict 15 time by days.

I have rebased all the master commits, so, I don't have any conflict for the moment.

You can test it by using:
```shell
$ vagrant init archlinux/archlinux
$ vagrant up
$ vagrant ssh # connect to archlinux with vagrant
[vagrant]$ curl https://raw.githubusercontent.com/4383/vespene/packaging/install.sh > install.sh
[vagrant]$ sudo bash install.sh --repo=4383 --branch=packaging
[vagrant]$ vespene setup
```

Thoughts? Likes?

**Comment by mpdehaan** [comment]
assuming we move that to reference the install script into the repo, and into the 'setup/' directory specifically of course, this is getting closer.

Can we make it default to the upstream repo and master?

I may decide to split the setup into two parts but that can obviously come later once I start fiddling with it.

I think this part of the code is perhaps too idiomatic and I don't understand what it does or how to work on it.  Breaking it into more lines with some variables/comments may help:

https://github.com/4383/vespene/blob/packaging/vespene/__main__.py#L45

Obviously I can dig in as I test it out.

I don't see when I am reading the __main__.py (also __main__.py seems to be a convention I am unfamiliar with?) what all that does.

I also don't want to adopt the dependency on pbr as I'm unfamiliar with what that does as the moment and I want to keep dependencies down.

**Comment by mpdehaan** [comment]
I don't want to waste your time on this when I am possibly being unclear, btw, so let me be a little more blunt than I would ordinarily be.

Right now, I don't see this as much of an improvement - that's not to say it isn't, but right now this obfuscates some things that used to be direct.

I'm kind of going to need it explained to me why it's better so I understand, otherwise, I think it makes it harder to tell what calls what, and harder to decide what to go into the shell scripts and edit them when customizing.

For instance, right now, people who are trying to dockerize things but may not have tons of Python experience can just read 1-6 and quickly find out what is up, but in this scenario, while the source of 1-6 is there, they are being called in a way that is somewhat harder to figure out.

So I'm not sure it's actually better?  

I'm not saying it's not, but right now I'm not convinced because I don't understand what the seperate-DB or embedded DB or config process would be like.  And right now, I know what that is because we ask you to edit 0_common.sh before installing.

So perhaps we can say "wget this defaults file" and then run that, and wget that, but at that point pypi is only there in such a small way, and perhaps this all feels weird as pypi is really good for libraries, but is not meant for applications.

As such, maybe we want to just not do this?

Sorry for being confused here, but I kind of am.

**Comment by 4383** [comment]
Hey @mpdehaan,

No problems.

I fully understand your point of vues, and your doubts, and To he honest with you , since yesterday I share your doubts, and during these few hours of development I ask myself about the real adding of this feature, so... only the install script is a plus and the rest of it is just a python wrapper (cli) around you shell setup and you are right it's more simple To understand by reading directly these scripts than dig my wrapper.

I originaly open create this PR to simplify the installation, and during the development I had imagined a tiny CLI, but currently this CLI just wrapp your setup scripts.

But it doesn't matter, I've learn lot of tips during this development, so don't worry be happy :)

I chosen to close it.
See you.

**Pull request closed without merging**
