### PR TITLE
fix archlinux useradd/adduser

### PR DESCRIPTION
**Pull request by 4383**
Error when we try to create the vespene user on archlinux with adduser

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ha distros are great aren’t they?

To clarify, it doesn’t have the more low-level useradd at all there? Adduser likes to ask for names and email addresses by default on some platforms.

**Comment by 4383** [comment]
@mpdehaan yep it's nice to meet issue like this during other tests lol.

adduser is not available by default I need to add the `AUR` repo to install it.
I change my fix to add AUR and install adduser instead using useradd.

**Comment by 4383** [comment]
```shell
$ vagrant init archlinux/archlinux
$ vagrant up
$ vagrant ssh # connect to archlinux with vagrant
[vagrant@archlinux ~]$ sudo pacman --noconfirm -Sy git
[vagrant@archlinux ~]$ git clone -b fix-adduser https://github.com/4383/vespene.git ./vespene
[vagrant@archlinux ~]$ cd vespene/setup/
[vagrant@archlinux ~]$ sudo bash 1_prepare.sh
```

**Comment by 4383** [comment]
doesn't work...

**Comment by 4383** [comment]
So my changes works but adduser ask for user informations

**Comment by 4383** [comment]
@mpdehaan after a a lot of changes and tests (install adduser, try to use useradd, etc...), I think the more preferable solution is to use useradd.

pro:
- useradd accept parameters and doesn't ask something.
- useradd is installed by default on archlinux
cons:
- adduser ask a lot of informations.
- adduser is not installed by default

What do you prefer?

**Comment by 4383** [comment]
I can introduce useradd only for archlinux in a first time and after switch on all distros

**Comment by mpdehaan** [comment]
I had already coded the install scripts to use useradd recently so yes useradd everywhere is good - so do we need the PR?

**Comment by mpdehaan** [comment]
So the codebase should already be using useradd everywhere so does there need to be anything done at all?

**Comment by 4383** [comment]
@mpdehaan where is it?
If you share it I can rebase my code with it and we can close this PR

**Comment by 4383** [comment]
else merge it temporary and I adapte if needed

**Comment by kdbeall** [comment]
@4383 @mpdehaan How about something like this?

if [ "$DISTRO" != "MacOS" ]; then
    if [ -x "$(command -v adduser)"  ]; then
        sudo adduser vespene
    else
        sudo useradd vespene
    fi
fi

**Comment by 4383** [comment]
@kdbeall personnally I agress

**Comment by 4383** [comment]
@kdbeall eventually for my temporary version but not for the next times

**Comment by mpdehaan** [comment]
actually what i really want is "useradd" on all platforms unless it is not there at all.

useradd is the basic low level one

adduser is the annoying one that frequently goes interactive and asks about email addresses

**Comment by mpdehaan** [comment]
https://github.com/vespene-io/vespene/commit/991a7bc1edc33cee36f187b2e4c737a7db1e51eb

**Pull request closed without merging**
